<?php
if (!defined('ABSPATH')) exit;
function cdp_customer_downloads_shortcode(){
 if(!is_user_logged_in()) return '<div class="cdp-portal"><p>Please login to view your customer portal.</p></div>';
 global $wpdb; $user_id=get_current_user_id(); $tab=sanitize_key($_GET['cdp_tab']??'downloads'); $allowed=['downloads','licenses','release-notes','documentation','support-tickets']; if(!in_array($tab,$allowed,true)) $tab='downloads';
 ob_start(); echo '<div class="cdp-portal"><style>.cdp-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 16px}.cdp-tabs a{padding:8px 12px;border:1px solid #ddd;text-decoration:none;border-radius:4px}.cdp-tabs a.active{font-weight:700;background:#f5f5f5}.cdp-card{border:1px solid #ddd;padding:14px;margin:0 0 12px;border-radius:6px}.cdp-table{width:100%;border-collapse:collapse}.cdp-table th,.cdp-table td{border:1px solid #ddd;padding:8px;text-align:left}.cdp-muted{color:#666}</style>';
 $tabs=['downloads'=>'Downloads','licenses'=>'Licenses','release-notes'=>'Release Notes','documentation'=>'Documentation','support-tickets'=>'Support Tickets']; echo '<nav class="cdp-tabs">'; foreach($tabs as $k=>$label){ $url=esc_url(add_query_arg('cdp_tab',$k)); echo '<a class="'.esc_attr($tab===$k?'active':'').'" href="'.$url.'">'.esc_html($label).'</a>'; } echo '</nav>';
 if($tab==='downloads') cdp_render_portal_downloads($user_id); elseif($tab==='licenses') cdp_render_portal_licenses($user_id); elseif($tab==='release-notes') cdp_render_portal_release_notes($user_id); elseif($tab==='documentation') cdp_render_portal_documentation($user_id); else cdp_render_portal_support();
 echo '</div>'; return ob_get_clean();
}
function cdp_render_portal_downloads($user_id){ global $wpdb; $a=cdp_table('assignments'); $p=cdp_table('products'); $v=cdp_table('product_versions'); $rows=$wpdb->get_results($wpdb->prepare("SELECT a.*, p.title, COALESCE(ver.version_label, latest.version_label) version_label, COALESCE(ver.release_date, latest.release_date) release_date FROM $a a JOIN $p p ON p.id=a.product_id LEFT JOIN $v ver ON ver.id=a.version_id LEFT JOIN $v latest ON latest.product_id=a.product_id AND latest.is_latest=1 AND latest.active=1 WHERE a.user_id=%d ORDER BY p.title",$user_id)); echo '<h2>Downloads</h2>'; if(!$rows){echo '<p>No downloads have been assigned to your account yet.</p>'; return;} foreach($rows as $r){ echo '<div class="cdp-card"><h3>'.esc_html($r->title).'</h3><p class="cdp-muted">Version: '.esc_html($r->version_label?:'Latest').($r->release_date?' · Released: '.esc_html($r->release_date):'').'</p><p>Downloads: '.esc_html($r->download_count.' / '.($r->max_downloads?:'Unlimited')).' · Expires: '.esc_html($r->expires_at?:'Never').'</p><p><a class="button" href="'.esc_url(cdp_download_url($r->token)).'">Download</a></p></div>'; }}
function cdp_render_portal_licenses($user_id){ global $wpdb; $rows=$wpdb->get_results($wpdb->prepare("SELECT l.*, p.title FROM ".cdp_table('licenses')." l JOIN ".cdp_table('products')." p ON p.id=l.product_id WHERE l.user_id=%d ORDER BY l.end_date DESC",$user_id)); echo '<h2>Licenses</h2>'; if(!$rows){echo '<p>No license records have been assigned to your account yet.</p>'; return;} echo '<table class="cdp-table"><thead><tr><th>Product</th><th>Subscription Plan</th><th>Quantity</th><th>Start Date</th><th>End Date</th><th>Status</th></tr></thead><tbody>'; foreach($rows as $r){ echo '<tr><td>'.esc_html($r->title).'</td><td>'.esc_html($r->subscription_plan).'</td><td>'.esc_html($r->quantity).'</td><td>'.esc_html($r->start_date).'</td><td>'.esc_html($r->end_date).'</td><td>'.esc_html(cdp_status_for_dates($r->start_date,$r->end_date)).'</td></tr>'; } echo '</tbody></table>'; }
function cdp_render_portal_release_notes($user_id){ global $wpdb; $ids=cdp_get_assigned_product_ids($user_id); echo '<h2>Release Notes</h2>'; if(!$ids){echo '<p>No release notes are available.</p>'; return;} $in=implode(',',array_map('absint',$ids)); $rows=$wpdb->get_results("SELECT v.*, p.title FROM ".cdp_table('product_versions')." v JOIN ".cdp_table('products')." p ON p.id=v.product_id WHERE v.active=1 AND v.product_id IN ($in) ORDER BY p.title, v.release_date DESC, v.id DESC"); if(!$rows){echo '<p>No release notes are available.</p>'; return;} foreach($rows as $r){ echo '<div class="cdp-card"><h3>'.esc_html($r->title).' — '.esc_html($r->version_label).'</h3><p class="cdp-muted">Released: '.esc_html($r->release_date?:'N/A').'</p><div>'.wp_kses_post(wpautop($r->release_notes?:'No release notes provided.')).'</div></div>'; }}
function cdp_render_portal_documentation($user_id){ global $wpdb; $ids=cdp_get_assigned_product_ids($user_id); echo '<h2>Documentation</h2>'; if(!$ids){echo '<p>No documentation is available.</p>'; return;} $in=implode(',',array_map('absint',$ids)); $rows=$wpdb->get_results("SELECT a.*, p.title product_title FROM ".cdp_table('product_assets')." a JOIN ".cdp_table('products')." p ON p.id=a.product_id WHERE a.active=1 AND a.asset_type IN ('documentation','video','kb') AND a.product_id IN ($in) ORDER BY p.title, a.sort_order, a.title"); if(!$rows){echo '<p>No documentation is available.</p>'; return;} foreach($rows as $r){ $link=$r->external_url ?: '#'; $file_label=$r->file_name ?: basename((string)$r->file_path); echo '<div class="cdp-card"><h3>'.esc_html($r->product_title).': '.esc_html($r->title).'</h3><p class="cdp-muted">'.esc_html(ucwords(str_replace('_',' ',$r->asset_type))).'</p><p>'.esc_html($r->description).'</p>'; if($r->external_url) echo '<p><a class="button" target="_blank" rel="noopener" href="'.esc_url($link).'">Open</a></p>'; if(($r->file_path || $r->file_name) && function_exists('cdp_asset_download_url')) echo '<p><a class="button" href="'.esc_url(cdp_asset_download_url($r->id)).'">Download File</a>'.($file_label ? ' <span class="cdp-muted">'.esc_html($file_label).'</span>' : '').'</p>'; echo '</div>'; }}
function cdp_render_portal_support(){ $email=get_option('cdp_support_email',''); $phone=get_option('cdp_support_phone',''); $url=get_option('cdp_support_url',''); echo '<h2>Support Tickets</h2><div class="cdp-card"><p>Need help? Contact support using the information below.</p>'; if($email) echo '<p>Email: <a href="mailto:'.esc_attr($email).'">'.esc_html($email).'</a></p>'; if($phone) echo '<p>Phone: '.esc_html($phone).'</p>'; if($url) echo '<p><a class="button" target="_blank" rel="noopener" href="'.esc_url($url).'">Open Support Portal</a></p>'; if(!$email&&!$phone&&!$url) echo '<p>Support contact details have not been configured yet.</p>'; echo '</div>'; }
